[package]
name = "gcp-access-token"
version = "0.2.0"
authors = ["Yong Wen Chua <lawliet89@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
env_logger = "0.7"
failure = "0.1.6"
hyper = "0.12"
hyper-tls = "0.3"
serde_json = "1.0"
tokio = "0.1"
yup-oauth2 = "3.0.2-beta"
